### ISSUE TITLE
How can I handle a date quite far away?

### ISSUE THREAD

**Issue by wisnuvb** [xeonx/timeago#8]
I tried to use to convert the data far enough, but did not generate the desired data. I entered 91008167 in seconds. Then I got the result 2021-02-25.

`waktu := time.Now().Add(91008167 * time.Second)`
`waktuString := timeago.English.Format(waktu)`
`fmt.Println(waktuString)`

But if the number 91008167 I change to 9100 can get the expected value. I got the result "in 3 hours".

**Comment by xeonx** [comment]
You may setup the Max configuration parameter (by default all dates in more than 3 days are displayed with full date like 2021-02-25 instead of"in 3 years").

`timeago.English.Max = 100 * 365 * 24 * time.Hour`

**Comment by wisnuvb** [comment]
Okay, thank you. I will try it
